apiVersion: apps/v1
kind: Deployment
metadata:
  name: udacity-project5
  labels:
    app: udacity-project5
spec:
  replicas: 1
  selector:
    matchLabels:
      app: udacity-project5
  strategy:
    rollingUpdate:
    #  maxSurge: 25%
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: udacity-project5
    spec:
      containers:
      - name: udacity-project5
        image: 230793/udacity-project-5:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 80


---
apiVersion: v1
kind: Service
metadata:
  name: udacity-project5
spec:
  type: LoadBalancer
  selector:
    app: udacity-project5
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
