version: 2.1

orbs:
  aws-eks: circleci/aws-eks@2.1.2
  kubernetes: circleci/kubernetes@1.3


executors:
  python:
    docker:
      - image: circleci/python:3.7.3-stretch
  aws:
    docker:
      - image: amazon/aws-cli

jobs:
  lint:
    executor: python
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "requirements.txt" }}
            - v1-dependencies-
      - run:
          name: install dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            make install
            # Install hadolint
            wget -O ./hadolint https://github.com/hadolint/hadolint/releases/download/v1.16.3/hadolint-Linux-x86_64 &&\
            chmod +x ./hadolint
            
      - save_cache:
          paths:
            - ./venv
          key: v1-dependencies-{{ checksum "requirements.txt" }}
      - run:
          name: run lint
          command: |
            . venv/bin/activate
            make lint

  build-push-image-to-registry:
    executor: python
    steps:
      - checkout
            
      - setup_remote_docker:
          version: 20.10.12
          docker_layer_caching: true

      - run:
          name: build an image
          command: |
            chmod +x ./scripts/build.sh
            ./scripts/build.sh
      - run:
          name: push an image to registry
          command: |
            chmod +x ./scripts/upload.sh
            ./scripts/upload.sh

workflows:
  udacity-project-5:
    jobs:
      - lint
      - build-push-image-to-registry:
          requires: [lint]